#!/usr/bin/env node

var mongojs = require('mongojs')
var randstr = require('randomstring').generate
var _       = require('underscore')
var db      = mongojs('trap')
var mines   = db.collection('mines')
var players = db.collection('players')

mines.drop()
players.drop()

mines.insert([
    {
        _id: mongojs.ObjectId("537e48763511c15161a1ed9f"),
        active: true,
        location: {type:'Point', coordinates:[-93.1512663, 44.460136]},
        owner: mongojs.ObjectId("537e48763511c15161a1ed9b"),
    },
    {
        _id: mongojs.ObjectId("537e48763511c15161a1ed9d"),
        active: true,
        location: {type:'Point', coordinates:[-93.1512731, 44.46015]},
        owner: mongojs.ObjectId("537d2b84221e2a193a385e40"),
    },
    {
        _id: mongojs.ObjectId("537e48763511c15161a1ed9e"),
        active: true,
        location: {type:'Point', coordinates:[-93.1512796, 44.4601341]},
        owner: mongojs.ObjectId("537e48763511c15161a1ed9c"),
    },
])

players.insert([
    {
        _id: mongojs.ObjectId("537e48763511c15161a1ed9b"),
        name: "Daniel",
        email: "maegereg@gmail.com",
        score: 500,
    },
    {
        _id: mongojs.ObjectId("537e48763511c15161a1ed9c"),
        name: "Calder",
        email: "caldercoalson@gmail.com",
        score: 500,
    },
])

players.insert([
    {name:"John", score:31, email:randstr()},
    {name:"William", score:46, email:randstr()},
    {name:"Charles", score:36, email:randstr()},
    {name:"George", score:62, email:randstr()},
    {name:"Admiral Akbar", score:1983, email:randstr()},
    {name:"Daniel Alexander Simmons Marengo The First", score:2000, email:"maegereg@gmail.com"},
    {name:"Mattathias", score:285, email:randstr()},
    {name:"Jeff Ondich", score:1337, email:randstr()},
    {name:"Mary", score:38, email:randstr()},
    {name:"Anna", score:341, email:randstr()},
    {name:"Elizabeth", score:54, email:randstr()},
    {name:"Margaret", score:545, email:randstr()},
    {name:"Ada", score:187, email:randstr()},
    {name:"Frantiska", score:49, email:randstr()},
    {name:"Helen", score:65, email:randstr()},
])

db.close()